name: solucion-CI

on: pull_request

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
     
      - name: set up jdk 17
        uses: actions/setup-java@v5.0.0
        with:
          distribution: adopt
          java-version: 17
      - run: mvn package -DskipTests
      - run: mvn test
